Develop
vezas/counter-app pull request #1
Opened 2022-10-10 08:52 UTC by vezas

2022-10-10 10:31 UTC, Aliath requested changes

2022-10-10 10:31 UTC, Aliath commented on src/components/UI/Card.tsx
> +export default Card;
I prefer not to use default export – it's easier to make a mistake and import wrong component with this

2022-10-10 10:31 UTC, Aliath commented on src/App.tsx
> +  const valueHandler = (value: number) => setCurrentValue(value);
There's no point with creating function that only calls another function – let's get rid of it

2022-10-11 07:12 UTC, vezas commented on src/components/counter/Counter.tsx
> +import { CounterProps } from '../../interfaces';
You are right, its better and cleaner way to import sth.

2022-10-11 07:15 UTC, vezas commented on src/components/counter/Counter.tsx
> +import { CounterProps } from '../../interfaces';
Probably, I saw a lot solution with exporting/importing interfaces/types. I thought that its common solution in React to keep it in external file.

2022-10-11 07:17 UTC, vezas commented on src/components/counter/Counter.tsx
> +    props.onValueHandler(currentValue);
Can u explain more? U mean that I shouldnt use useEffect? Without that it worked like async function. I had problem with  pass correct value to another file.

2022-10-11 07:17 UTC, vezas commented on src/App.tsx
> +  const valueHandler = (value: number) => setCurrentValue(value);
Yes, thats right.

2022-10-11 07:19 UTC, vezas commented on src/components/UI/Card.tsx
> +export default Card;
Probably in bigger projects. In small one like this it shouldn't genereate mistakes with wrong imports.

2022-10-11 07:22 UTC, vezas commented on src/components/UI/Button.module.css
> +  margin: 0 5vw;
I wanted to make this components easily responsive. So it has to be stupid habbit. So in paddings we shouldnt use vw/vh, should we?

2022-10-11 07:23 UTC, vezas commented on src/components/UI/Button.module.css
> +button:hover {
Scss is good practise, I will try to use it in next project.

2022-10-11 07:25 UTC, vezas commented on src/components/UI/Card.tsx
> +const Card: React.FC<CardProps> = (props) => {
I saw that solution too. In that case its easy to do that like u, but what in the case when we have 5/10 or more props? Wouldnt it look weird or sth?

2022-10-11 07:28 UTC, vezas commented on src/components/counter/Counter.tsx
> +    setCurrentValue((prevValue) => prevValue! + 1);
I tried ur soultion from Mattermost (currentValue === null) but I still cant avoid error. I will leave few solution in file in comments. U can try to give me right solution. Maybe there is any problem with types or sth.

2022-10-11 07:33 UTC, vezas commented on src/components/result/Result.module.css
> +.result div {
Using element selector with module.css isn't good solution? Parent elements get their own class so its difficult to get any issues.
Also elements in code are smaller/leaner.

2022-10-11 08:28 UTC, Aliath commented on src/components/result/Result.module.css
> +.result div {
It isn't in general – it's hard to anticipate how your application is going to grow up and with what it can be expanded with, if you add some div element to your component you can face dozen of issues related with applied styles that you don't want

https://frontstuff.io/you-need-to-stop-targeting-tags-in-css

2022-10-11 08:31 UTC, vezas commented on src/components/result/Result.tsx
> +    if (props.value) prevValueRef.current!.innerText = props.value!.toString();
I deleted innerText, check if its correct now.

2022-10-11 08:32 UTC, Aliath commented on src/components/counter/Counter.tsx
> +    props.onValueHandler(currentValue);
In react you have two patterns for handling the mechanics behind component

you can either allow component to control its state by its own (it's mostly used in UI-only stuff that does not reflect any state changes or such) or you can control it from its parent (the component is driven by two properties – mostly `[value]` and `[onChange]` and component only calls/uses it from the parent)

You shouldn't mix them together because it's extremely hard to debug this, find the real source of data and control this the proper way (e.g. setting value from parent is impossible with this approach)

2022-10-11 08:38 UTC, Aliath commented on src/components/UI/Card.tsx
> +const Card: React.FC<CardProps> = (props) => {
It depends – in general it's better to extrude them because you don't have to repeat `props.` over whole component, it also forces you to name your variables/functions without any collisions

Although there's one exception when you are passing set of properties to the child component, it's pretty common and can be resolved this way:

```tsx
interface CardProps {
  type: string;
  className?: string;
  onChange: (value: string) => void;
}

// we want to pass `[type]` property to `<Wrapper>` but rest of them to `<Component>`
const Card = ({ type, ...props }: CardProps) => {
  return (
    <Wrapper type={type}>
      <Component {...props} />
    </Wrapper>
  );
}

2022-10-11 08:38 UTC, Aliath commented on src/components/UI/Button.module.css
> +button:hover {
You can try to apply it to this one ;)

2022-10-11 08:38 UTC, Aliath commented on src/App.tsx
> +      <Counter onValueHandler={valueHandler} />
Have describe this several comments above

2022-10-11 08:41 UTC, Aliath commented on src/components/UI/Card.tsx
> +export default Card;
Not really – if the functionality of language allows you to reduce potential mistakes in code – don't hesitate to apply it

If some component exports more than one thing (what's a common case) then you don't have to wonder which value is exported as a default one, if you change the value behind default export – in some cases it may be hard to reflect the change in places that use it

2022-10-11 08:56 UTC, Aliath commented on src/components/UI/Button.module.css
> +  margin: 0 5vw;
It shouldn't

Your components (especially generic ones) should be bulletproof – you never know where another developer will place them and how `vw` will affect the position of them

Your generic components such as button should do absolutely minimum – all the things such as margin, etc. should be applied on higher level (e.g. if your view contains a button – it can also extend its styles for the view's needs)

2022-10-11 08:58 UTC, Aliath commented on src/components/UI/Button.module.css
> +  margin: 0 5vw;
`vw` and `vh` make things much harder when it comes to RWD

to wrap up – whenever you can avoid using `vw` and `vh` – simply do it

2022-10-12 06:31 UTC, Aliath approved these changes
💪

2022-10-12 06:31 UTC, Aliath commented on src/components/UI/Button.tsx
> +  onChange: () => void | any;
```suggestion
  onClick: () => void;
```

2022-10-12 06:31 UTC, Aliath commented on src/App.tsx
> +  const [currentValue, setCurrentValue] = useState<number | null>(null);
Actually you don't have to have `null` value for counter – counter should start with `0` value but `previousValue` (defined in another component) can be nullish

2022-10-12 06:31 UTC, Aliath commented on src/App.tsx
> +  const [currentValue, setCurrentValue] = useState<number | null>(null);
^^ so that I would replace all types `number | null` that refers to value with `number`

2022-10-12 06:31 UTC, Aliath commented on src/components/UI/Button.tsx
> +export { Button };
You can export it with definition:
```tsx
export const Button: React.FC<ButtonProps> = (props) => {

2022-10-12 06:31 UTC, Aliath commented on src/components/UI/Card.tsx
> +  className?: string | undefined;
You don't have to specify undefined if you have `?` character at the end of field

2022-10-13 09:19 UTC, merged